source 'https://rubygems.org'
gem 'logger'
gem 'sinatra'
gem 'pry'
gem 'haml'
gem 'addressable', require: 'addressable/uri'
gem 'builder'
gem 'capybara'
gem 'poltergeist', "1.10.0", require: 'capybara/poltergeist'
gem 'phantomjs', "2.1.1", :require => 'phantomjs/poltergeist'
gem 'thin'
gem 'sinatra-contrib'
